### ISSUE TITLE
Tracker evaluate on KITTI dataset but has format error

### ISSUE THREAD

**Issue by chenx1e** [JonathonLuiten/TrackEval#132]
Hi, thanks for the amazing work! I download the example gt and trackers in KITTI dataset and running successful, but the trackrcnn results text file you provided are messy on my Window10 computer:
![image](https://github.com/JonathonLuiten/TrackEval/assets/71810129/b6212b96-add7-4bfd-9a83-0971cc927c89)

I prepared my own tracker results text file following KITTI format, and want to evaluate this tracker, but has format error in `load_raw_file` process.
`Traceback (most recent call last):
  File "E:\codes\TrackEval\trackeval\datasets\kitti_mots.py", line 212, in _load_raw_file
    raw_data['dets'][t] = [{'size': [int(region[3]), int(region[4])],
  File "E:\codes\TrackEval\trackeval\datasets\kitti_mots.py", line 212, in <listcomp>
    raw_data['dets'][t] = [{'size': [int(region[3]), int(region[4])],
ValueError: invalid literal for int() with base 10: '0.00'`

My tracker format is:
![image](https://github.com/JonathonLuiten/TrackEval/assets/71810129/a47cdbb9-9978-42d8-95f9-7f976af14e23)

Could any one help me?

**Comment by chenx1e** [comment]
The script I run is `scripts/run_kitti_mots.py`

**Comment by mikochinya** [comment]
Hi, I'm dealing with the same issue here. Do you have any solutions?
