### ISSUE TITLE
I encountered an error and don't know how to solve it

### ISSUE THREAD

**Issue by zeng121** [JonathonLuiten/TrackEval#141]
Traceback (most recent call last):
  File "F:\pythonProject\TrackEval\scripts\run_mot_challenge.py", line 84, in <module>
    dataset_list = [trackeval.datasets.MotChallenge2DBox(dataset_config)]
  File "F:\pythonProject\TrackEval\trackeval\datasets\mot_challenge_2d_box.py", line 83, in __init__
    self.seq_list, self.seq_lengths = self._get_seq_info()
  File "F:\pythonProject\TrackEval\trackeval\datasets\mot_challenge_2d_box.py", line 163, in _get_seq_info
    if i == 0 or row[0] == '':
IndexError: list index out of range

**Comment by JonathonLuiten** [comment]
looks like your data is empty, such that row has no data and row[0] doesn't exist
