### ISSUE TITLE
Error while running the python3 scripts/run_rob_mots.py --ROBMOTS_SPLIT train --TRACKERS_TO_EVAL STP --USE_PARALLEL True --NUM_PARALLEL_CORES 4

### ISSUE THREAD

**Issue by shivakarnati** [JonathonLuiten/TrackEval#149]
Hello @JonathonLuiten , 

Thank you for the great work. I was trying `RobMOTS-Official/Readme.md ` specified script, but I encountered below error. Could you please help me to figure out?

Installations:
- python 3.5.0
- requirements.txt

```
/TrackEval$ python3 scripts/run_rob_mots.py --ROBMOTS_SPLIT train --TRACKERS_TO_EVAL STP --USE_PARALLEL True --NUM_PARALLEL_CORES 4
Traceback (most recent call last):
  File "scripts/run_rob_mots.py", line 10, in <module>
    import trackeval  # noqa: E402
  File "/home/shivakrishnakarnati/Documents/Programming/ML_projects/TrackEval/trackeval/__init__.py", line 2, in <module>
    from . import datasets
  File "/home/shivakrishnakarnati/Documents/Programming/ML_projects/TrackEval/trackeval/datasets/__init__.py", line 13
    print(f"Error importing BURST due to missing underlying dependency: {err}")
                                                                             
SyntaxError: invalid syntax
```

**Comment by shivakarnati** [comment]
```
from .burst import BURST
from .burst_ow import BURST_OW
# try:
    #from .burst import BURST
    #from .burst_ow import BURST_OW
# except ImportError as err:
#     print(f"Error importing BURST due to missing underlying dependency: {err}")

```

commented trackeval/datasets/__init__.py
