### ISSUE TITLE
Run from scripts folder does not work

### ISSUE THREAD

**Issue by dcallega** [JonathonLuiten/TrackEval#19]
I created a clean virtual environment with python3, installed numpy and scipy. I also downloaded the data.zip and placed it in the main directory of this repository (same level as docs, scripts, tests, trackeval).
When I run the script from the main folder this happens:

./venv/bin/python3 scripts/run_kitti.py

Eval Config:
USE_PARALLEL         : False                         
NUM_PARALLEL_CORES   : 8                             
BREAK_ON_ERROR       : True                          
RETURN_ON_ERROR      : False                         
LOG_ON_ERROR         : /home/ias/git/TrackEval/error_log.txt
PRINT_RESULTS        : True                          
PRINT_ONLY_COMBINED  : False                         
PRINT_CONFIG         : True                          
TIME_PROGRESS        : True                          
DISPLAY_LESS_PROGRESS : True                          
OUTPUT_SUMMARY       : True                          
OUTPUT_EMPTY_CLASSES : True                          
OUTPUT_DETAILED      : True                          
PLOT_CURVES          : True                          

Kitti2DBox Config:
PRINT_CONFIG         : True                          
GT_FOLDER            : /home/ias/git/TrackEval/data/gt/kitti/kitti_2d_box_train
TRACKERS_FOLDER      : /home/ias/git/TrackEval/data/trackers/kitti/kitti_2d_box_train/
OUTPUT_FOLDER        : None                          
TRACKERS_TO_EVAL     : None                          
CLASSES_TO_EVAL      : ['car', 'pedestrian']         
SPLIT_TO_EVAL        : training                      
INPUT_AS_ZIP         : False                         
TRACKER_SUB_FOLDER   : data                          
OUTPUT_SUB_FOLDER    :                               
TRACKER_DISPLAY_NAMES : None                          

Evaluating 1 tracker(s) on 21 sequence(s) for 2 class(es) on Kitti2DBox dataset using the following metrics: HOTA, CLEAR, Identity, Count

Evaluating CIWT

Tracker CIWT was unable to be evaluated.
Ground-truth data contains the following invalid timesteps in seq 0000: 0, 
Traceback (most recent call last):
  File "/home/ias/git/TrackEval/trackeval/eval.py", line 87, in evaluate
    metric_names)
  File "/home/ias/git/TrackEval/trackeval/_timing.py", line 16, in wrap
    result = f(*args, **kw)
  File "/home/ias/git/TrackEval/trackeval/eval.py", line 187, in eval_sequence
    raw_data = dataset.get_raw_seq_data(tracker, seq)
  File "/home/ias/git/TrackEval/trackeval/_timing.py", line 16, in wrap
    result = f(*args, **kw)
  File "/home/ias/git/TrackEval/trackeval/datasets/_base_dataset.py", line 87, in get_raw_seq_data
    raw_gt_data = self._load_raw_file(tracker, seq, is_gt=True)
  File "/home/ias/git/TrackEval/trackeval/datasets/kitti_2d_box.py", line 187, in _load_raw_file
    [str(x) + ', ' for x in extra_time_keys]))
trackeval.utils.TrackEvalException: Ground-truth data contains the following invalid timesteps in seq 0000: 0, 
Traceback (most recent call last):
  File "scripts/run_kitti.py", line 86, in <module>
    evaluator.evaluate(dataset_list, metrics_list)
  File "/home/ias/git/TrackEval/trackeval/_timing.py", line 16, in wrap
    result = f(*args, **kw)
  File "/home/ias/git/TrackEval/trackeval/eval.py", line 177, in evaluate
    raise err
  File "/home/ias/git/TrackEval/trackeval/eval.py", line 87, in evaluate
    metric_names)
  File "/home/ias/git/TrackEval/trackeval/_timing.py", line 16, in wrap
    result = f(*args, **kw)
  File "/home/ias/git/TrackEval/trackeval/eval.py", line 187, in eval_sequence
    raw_data = dataset.get_raw_seq_data(tracker, seq)
  File "/home/ias/git/TrackEval/trackeval/_timing.py", line 16, in wrap
    result = f(*args, **kw)
  File "/home/ias/git/TrackEval/trackeval/datasets/_base_dataset.py", line 87, in get_raw_seq_data
    raw_gt_data = self._load_raw_file(tracker, seq, is_gt=True)
  File "/home/ias/git/TrackEval/trackeval/datasets/kitti_2d_box.py", line 187, in _load_raw_file
    [str(x) + ', ' for x in extra_time_keys]))
trackeval.utils.TrackEvalException: Ground-truth data contains the following invalid timesteps in seq 0000: 0,

**Comment by JonathonLuiten** [comment]
Hey thanks for pointing this out! This was actually an error that I introduces in the last 2 days when I was doing things too quick too tired.

Just made a commit that fixes this now! It should work for you now! :)

Thanks again for bringing this up, appreciate it ALOT!

Jono
