### ISSUE TITLE
Problem script run_davis.py 

### ISSUE THREAD

**Issue by ATrackerLearner** [JonathonLuiten/TrackEval#38]
Hi! 

Within the context of PR #36 I found the following problem. I found out that I can't execute scripts/run_davis.py, I have the following ouput error:
```
Eval Config:
USE_PARALLEL         : False                         
NUM_PARALLEL_CORES   : 8                             
BREAK_ON_ERROR       : True                          
RETURN_ON_ERROR      : False                         
LOG_ON_ERROR         : /home/muffie/code/TrackEval-master/error_log.txt
PRINT_RESULTS        : True                          
PRINT_ONLY_COMBINED  : False                         
PRINT_CONFIG         : True                          
TIME_PROGRESS        : True                          
DISPLAY_LESS_PROGRESS : True                          
OUTPUT_SUMMARY       : True                          
OUTPUT_EMPTY_CLASSES : True                          
OUTPUT_DETAILED      : True                          
PLOT_CURVES          : False                         

DAVIS Config:
PRINT_CONFIG         : True                          
GT_FOLDER            : /home/muffie/code/TrackEval-master/data/gt/davis/davis_unsupervised_val/
TRACKERS_FOLDER      : /home/muffie/code/TrackEval-master/data/trackers/davis/davis_unsupervised_val/
OUTPUT_FOLDER        : None                          
TRACKERS_TO_EVAL     : ['ags']                       
SPLIT_TO_EVAL        : val                           
CLASSES_TO_EVAL      : ['general']                   
TRACKER_SUB_FOLDER   : data                          
OUTPUT_SUB_FOLDER    :                               
TRACKER_DISPLAY_NAMES : None                          
SEQMAP_FILE          : None                          
SEQ_INFO             : None                          
MAX_DETECTIONS       : 0                             

Evaluating 1 tracker(s) on 30 sequence(s) for 1 class(es) on DAVIS dataset using the following metrics: HOTA, Count


Evaluating ags

Tracker ags was unable to be evaluated.
numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
Traceback (most recent call last):
  File "/home/muffie/code/TrackEval-master/trackeval/eval.py", line 86, in evaluate
    res[curr_seq] = eval_sequence(curr_seq, dataset, tracker, class_list, metrics_list,
  File "/home/muffie/code/TrackEval-master/trackeval/_timing.py", line 16, in wrap
    result = f(*args, **kw)
  File "/home/muffie/code/TrackEval-master/trackeval/eval.py", line 187, in eval_sequence
    raw_data = dataset.get_raw_seq_data(tracker, seq)
  File "/home/muffie/code/TrackEval-master/trackeval/_timing.py", line 16, in wrap
    result = f(*args, **kw)
  File "/home/muffie/code/TrackEval-master/trackeval/datasets/_base_dataset.py", line 87, in get_raw_seq_data
    raw_gt_data = self._load_raw_file(tracker, seq, is_gt=True)
  File "/home/muffie/code/TrackEval-master/trackeval/datasets/davis.py", line 123, in _load_raw_file
    from pycocotools import mask as mask_utils
  File "/home/muffie/.local/lib/python3.8/site-packages/pycocotools/mask.py", line 3, in <module>
    import pycocotools._mask as _mask
  File "pycocotools/_mask.pyx", line 1, in init pycocotools._mask
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
Traceback (most recent call last):
  File "scripts/run_davis.py", line 90, in <module>
    evaluator.evaluate(dataset_list, metrics_list)
  File "/home/muffie/code/TrackEval-master/trackeval/_timing.py", line 16, in wrap
    result = f(*args, **kw)
  File "/home/muffie/code/TrackEval-master/trackeval/eval.py", line 177, in evaluate
    raise err
  File "/home/muffie/code/TrackEval-master/trackeval/eval.py", line 86, in evaluate
    res[curr_seq] = eval_sequence(curr_seq, dataset, tracker, class_list, metrics_list,
  File "/home/muffie/code/TrackEval-master/trackeval/_timing.py", line 16, in wrap
    result = f(*args, **kw)
  File "/home/muffie/code/TrackEval-master/trackeval/eval.py", line 187, in eval_sequence
    raw_data = dataset.get_raw_seq_data(tracker, seq)
  File "/home/muffie/code/TrackEval-master/trackeval/_timing.py", line 16, in wrap
    result = f(*args, **kw)
  File "/home/muffie/code/TrackEval-master/trackeval/datasets/_base_dataset.py", line 87, in get_raw_seq_data
    raw_gt_data = self._load_raw_file(tracker, seq, is_gt=True)
  File "/home/muffie/code/TrackEval-master/trackeval/datasets/davis.py", line 123, in _load_raw_file
    from pycocotools import mask as mask_utils
  File "/home/muffie/.local/lib/python3.8/site-packages/pycocotools/mask.py", line 3, in <module>
    import pycocotools._mask as _mask
  File "pycocotools/_mask.pyx", line 1, in init pycocotools._mask
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
```

___

### Steps to reproduce:
- `git clone https://github.com/JonathonLuiten/TrackEval`
- add [data folder](https://omnomnom.vision.rwth-aachen.de/data/TrackEval/data.zip) to root dir of  the repo folder
- install local venv with depencies : `numpy==1.18.1, scipy==1.4.1, pycocotools==2.0.2, matplotlib==3.2.1, Pillow==8.1.2` according to [requirements.txt](https://github.com/JonathonLuiten/TrackEval/blob/master/requirements.txt)
- `python scripts/run_davis.py --USE_PARALLEL False --METRICS HOTA --TRACKERS_TO_EVAL ags --PLOT_CURVES False`

**Also, DAVIS evaluation needs pycocotools which is not in [minimal_requirements.txt](https://github.com/JonathonLuiten/TrackEval/blob/master/minimum_requirements.txt)**. Also pycocotools module relies on matplotlib + pillow.  According to [this README](https://github.com/JonathonLuiten/TrackEval#properties-of-this-codebase), I think these depencies should be added to minimal requirements in order to run on DAVIS dataset as intended

**Update:** Same problem with KITTI MOTS, MOTS Challenge and Youtube VIS. They both needs pycocotools that seems a core package for segmentation evaluation. And it got the exact same error.

**Comment by ATrackerLearner** [comment]
Hi, 

Finally, I solved this. It's not a problem with the scripts. 

I tried the steps to reproduce on another computer and it worked perfectly. 
I solved this issue by installing numpy == 1.20.1 instead of 1.18.1 and it worked on my current computer. ([thanks to SO](https://stackoverflow.com/questions/66060487/valueerror-numpy-ndarray-size-changed-may-indicate-binary-incompatibility-exp)). 

Although, I still point out the depencies that should be larger including pycocotools (so matplotlib and Pillow) that seem to be mandatory for evaluating MOTS datasets @JonathonLuiten . Correct me if I am wrong please. 

Thanks for your attention,
Have a great day! 

Mathias.
